### ISSUE TITLE
fitsio-1.1.0 install problem

### ISSUE THREAD

**Issue by paulkerry1** [esheldon/fitsio#288] opened 2020-02-24 13:16 UTC
Hi

I'm trying to install fitsio-1.1.0 using "pip3 install fitsio -U", but it fails with...

drvrnet.c:` In function ‘curlProgressCallback’:
drvrnet.c:1261:13: error: format not a string literal and no format arguments [-Werror=format-security]
             fprintf(stderr,urlname);

So I'm now trying the git cloned version as of date: "python3 setup.py build" fails with...
checking for main in -lbz2... no
configure: error: Unable to locate bz2 library needed when enabling bzip2 support; try specifying the path

so I installed the libbz2-dev o/s package and tried again which got further on, but this then fails in the "ValueError: could not compile cfitsio 3470" section with the same thing as pip3...

drvrnet.c: In function ‘curlProgressCallback’:
drvrnet.c:1261:13: error: format not a string literal and no format arguments [-Werror=format-security]
             fprintf(stderr,urlname);

This is on Debian amd64 with python 3.7.3

Cheers
Paul.

Additional info:
going into the git source build tree at fitsio/build/temp.linux-x86_64-3.7/cfitsio3470
I notice this in config.log

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.
It was created by configure, which was
generated by GNU Autoconf 2.69.  Invocation command line was
  $ ./configure --with-bzip2 --enable-standard-strings CC=x86_64-linux-gnu-gcc CFLAGS=-pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 ARCHIVE=x86_64-linux-gnu-gcc-ar rcs

That configure line doesn't look right to me: if I do a manual "./configure --with-bzip2 --enable-standard-strings" then that works, as does make in that folder, as does "python3 setup.py build" at the top level.

Possibly to do with the "+ args," in setup.py on line 220?

**Comment by beckermr** [comment] 2020-02-24 14:01
Yeah, those CFLAGS should be quoted.

**Comment by esheldon** [comment] 2020-02-24 14:27
This works on my setups, which are all linux.

I wonder if this has something to do with your environment

**Comment by paulkerry1** [comment] 2020-02-24 15:48
Which versions of things are you using and which linux variant?
I can successfully configure and make the bundled cfitsio3470 on it's own.
I cannot follow what you are doing here in setup.py with the "+ args" on line 220...
"sh ./configure --with-bzip2 --enable-standard-strings " + args,

What's the extra "+ args" for at this stage and how is that related to setting CC and CFLAGS from lines 210-212 in setup.py ?
If I remove "+ args" from setup.py, then manual building and pip3 install works fine.

**Comment by beckermr** [comment] 2020-02-24 15:51
The `+args` adds in the extra compilation flags.

**Comment by beckermr** [comment] 2020-02-24 15:53
What's odd is that somehow when your machine outputs the flags, they are no longer quoted. 

Can you send the exact output you get?

**Comment by esheldon** [comment] 2020-02-24 16:09
Works for me on ubuntu, rhel7 and arch linux all using anaconda python 3.7

**Comment by esheldon** [comment] 2020-02-24 16:14
I noticed your command was "pip3 install ..."  why is it pip3 not just pip?  Is this using the python 3 installation on debian through apt-get ?

**Comment by paulkerry1** [comment] 2020-02-24 20:31
I've figured it out - it looks like the same thing as described on..
https://wiki.ubuntu.com/ToolChain/CompilerFlags#A-Wformat_-Wformat-security
even though I'm on Debian.
Following the above and changing cfitsio3470/drvrnet.c line 1261
from...
fprintf(stderr,urlname);
to...
fprintf(stderr,"%s",urlname);

makes everything work perfectly, using pip3 and/or manual python3 building. I tried the same thing on Arch Linux as well and that also works perfectly.

Is this something you would be happy rolling out or will I have to manually patch the source when there is an update?

From completeness, I don't use anaconda and no it's not the apt-get version of pip for python: it's the latest pip I'm using manually downloaded and so it's the "pip3" command for python3.

Cheers
Paul

**Comment by esheldon** [comment] 2020-02-24 21:26
OK, this sounds like a potential fix.

1. I wonder if a newer cfitsio would have this fixed
2. if not is this a bug we need to pass bug report to the cfitsio maintainers?
3. we can add a patch if you submit a PR with it.  When you submit the PR it will fire off tests against our standard platforms at least

**Comment by LRenegar** [comment] 2020-02-27 18:14
I reproduced this on Python 3.6.8 and Ubuntu 18.04.3 LTS running under WSL on Windows 10. I've attached the build logs from both pip and from building the C library from the latest source  [tar](https://heasarc.gsfc.nasa.gov/fitsio/). I agree with @paulkerry1 's explanation above. It looks like installing from `pip` uses the flags in `CFLAGS`, including the offending `-Werror=format-security`, whereas compiling using the `configure` script shipped with the C library doesn't include that flag.

So, it's probably worth reporting to the `cfitsio` maintainers, but, since it compiles with their build script, a more immediate fix would be to remove the `-Werror=format-security` flag in the setup script, at least temporarily.

[fitsio_pip.txt](https://github.com/esheldon/fitsio/files/4263202/fitsio_pip.txt)
[cfitsio_gsfc.txt](https://github.com/esheldon/fitsio/files/4263203/cfitsio_gsfc.txt)

**Comment by saimn** [comment] 2020-02-27 19:19
We get a similar error when pip-installing fitsio on Travis:
```
    drvrnet.c: In function ‘curlProgressCallback’:
    drvrnet.c:1261:13: error: format not a string literal and no format arguments [-Werror=format-security]
                 fprintf(stderr,urlname);
```
https://travis-ci.org/musevlt/mpdaf/jobs/654218339

**Comment by tskisner** [comment] 2020-02-27 23:35
Just wanted to add a note that we use fitsio in various packages for the DESI project, and we have seen this error when building wheels or from source in the travis jobs for several branches:

https://github.com/desihub/fiberassign/pull/252
https://github.com/desihub/fiberassign/pull/253

Obviously it would be easiest for us to install from a release tag or PyPI version, but if that is not available soon we'll revert to local patching...

**Comment by beckermr** [comment] 2020-02-27 23:42
We need to explore a more sustainable model for cfitsio. Right now we have a situation where

1. bugs/features in cfitsio are being found via this project
2. we are patching in new features (UTF-8 support) and bug fixes (compression) in this 
  project in a pretty unsustainable way
3. we are not able to push some of these changes upstream for various reasons
4. any upstream changes are **emailed as diffs** to the maintainers at NASA

I don't want to be in the business of maintaining all of cfitsio and so a hard fork is out of the question. I'd be nice to at least have cfitsio in a repo visible on the web so that others can file issues and we can track when bugs get put upstream etc.

**Comment by beckermr** [comment] 2020-02-27 23:47
various people have resorted to simply posting release by hand on github

- https://github.com/healpy/cfitsio
- https://github.com/brianv0/cfitsio

or hard forks

- https://github.com/sfabbro/cfitsio

**Comment by beckermr** [comment] 2020-02-27 23:47
@brianv0 for viz

**Comment by tskisner** [comment] 2020-02-27 23:47
Ah, CFITSIO.  So many years of fun :-)  It looks like several projects have git repos of the source.  Is this the official one?

https://github.com/HEASARC/cfitsio

Others I see:

https://github.com/healpy/cfitsio
https://github.com/Starlink/cfitsio

**Comment by beckermr** [comment] 2020-02-27 23:47
hey starlink too!

**Comment by beckermr** [comment] 2020-02-27 23:48
last commit at https://github.com/HEASARC/cfitsio is from 2018 so no?

**Comment by tskisner** [comment] 2020-02-27 23:51
Yeah, looks like an official, but abandoned location.  As you say, forking (and maintaining) CFITSIO is a massive undertaking that no one wants.  Many years of legacy code using that.  And `git format-patch` workflows are retro but not ideal...

**Comment by esheldon** [comment] 2020-03-03 13:38
I agree the situation is not ideal.  But I think in any case we need a new release with a fix for this in the short term.  @paulkerry1 can you please submit a PR?

**Comment by esheldon** [comment] 2020-03-03 14:07
@paulkerry1 I realized we are doing this with patches rather than modifying the source itself, so this might not be so easy to follow.  I'll do the PR.

**Comment by paulkerry1** [comment] 2020-03-03 14:17
Thanks - I was just looking at doing a PR until your post.

**Comment by esheldon** [comment] 2020-03-03 14:36
The pr is in, #289 under branch urlname-format

Do those of you that h ave seen failures have the ability to check that brach to see if this works?

**Comment by LRenegar** [comment] 2020-03-03 15:05
It builds for me.

**Closed** 2020-03-06 15:31 UTC
