### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by astrom-tom** [esheldon/fitsio#229] opened 2019-04-24 06:08 UTC
Hi all,

Tonight I wanted to try out the new version of fitsio and I came up with the following error (using pip).
I am working in an Anaconda environment with python 3.7.3.

Any chance you could give me a hand?

Building wheels for collected packages: fitsio
  Building wheel for fitsio (setup.py) ... error
  Complete output from command /run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ui7d52yl/fitsio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-ztgsfpi1 --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/fitsio
  copying fitsio/util.py -> build/lib.linux-x86_64-3.7/fitsio
  copying fitsio/test.py -> build/lib.linux-x86_64-3.7/fitsio
  copying fitsio/fitslib.py -> build/lib.linux-x86_64-3.7/fitsio
  copying fitsio/__init__.py -> build/lib.linux-x86_64-3.7/fitsio
  running build_ext
  replacing '-O3' with '-O2' to address gcc bug
  checking file build/temp.linux-x86_64-3.7/cfitsio3430/configure.in
  patching file build/temp.linux-x86_64-3.7/cfitsio3430/configure.in
  checking file build/temp.linux-x86_64-3.7/cfitsio3430/configure
  patching file build/temp.linux-x86_64-3.7/cfitsio3430/configure
  checking file build/temp.linux-x86_64-3.7/cfitsio3430/fitscore.c
  patching file build/temp.linux-x86_64-3.7/cfitsio3430/fitscore.c
  checking file build/temp.linux-x86_64-3.7/cfitsio3430/fitsio.h
  patching file build/temp.linux-x86_64-3.7/cfitsio3430/fitsio.h
  checking file build/temp.linux-x86_64-3.7/cfitsio3430/imcompress.c
  patching file build/temp.linux-x86_64-3.7/cfitsio3430/imcompress.c
  checking file build/temp.linux-x86_64-3.7/cfitsio3430/putcols.c
  patching file build/temp.linux-x86_64-3.7/cfitsio3430/putcols.c
  checking build system type... x86_64-unknown-linux-gnu
  checking host system type... x86_64-unknown-linux-gnu
  checking target system type... x86_64-unknown-linux-gnu
  checking for gcc... gcc
  checking whether the C compiler works... no
  configure: error: in `/tmp/pip-install-ui7d52yl/fitsio/build/temp.linux-x86_64-3.7/cfitsio3430':
  configure: error: C compiler cannot create executables
  See `config.log' for more details
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-ui7d52yl/fitsio/setup.py", line 289, in <module>
      cmdclass={"build_ext": build_ext_subclass}
    File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-ui7d52yl/fitsio/setup.py", line 72, in run
      build_ext.run(self)
    File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-ui7d52yl/fitsio/setup.py", line 100, in build_extensions
      RANLIB=self.compiler.ranlib,
    File "/tmp/pip-install-ui7d52yl/fitsio/setup.py", line 227, in configure_cfitsio
      "could not configure cfitsio %s" % self.cfitsio_version)
  ValueError: could not configure cfitsio 3430
  
  ----------------------------------------
  Failed building wheel for fitsio
  Running setup.py clean for fitsio
Failed to build fitsio
Installing collected packages: fitsio
  Found existing installation: fitsio 0.9.11
    Uninstalling fitsio-0.9.11:
      Successfully uninstalled fitsio-0.9.11
  Running setup.py install for fitsio ... error
    Complete output from command /run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ui7d52yl/fitsio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-m6wfuawp/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/fitsio
    copying fitsio/util.py -> build/lib.linux-x86_64-3.7/fitsio
    copying fitsio/test.py -> build/lib.linux-x86_64-3.7/fitsio
    copying fitsio/fitslib.py -> build/lib.linux-x86_64-3.7/fitsio
    copying fitsio/__init__.py -> build/lib.linux-x86_64-3.7/fitsio
    running build_ext
    replacing '-O3' with '-O2' to address gcc bug
    checking file build/temp.linux-x86_64-3.7/cfitsio3430/configure.in
    patching file build/temp.linux-x86_64-3.7/cfitsio3430/configure.in
    checking file build/temp.linux-x86_64-3.7/cfitsio3430/configure
    patching file build/temp.linux-x86_64-3.7/cfitsio3430/configure
    checking file build/temp.linux-x86_64-3.7/cfitsio3430/fitscore.c
    patching file build/temp.linux-x86_64-3.7/cfitsio3430/fitscore.c
    checking file build/temp.linux-x86_64-3.7/cfitsio3430/fitsio.h
    patching file build/temp.linux-x86_64-3.7/cfitsio3430/fitsio.h
    checking file build/temp.linux-x86_64-3.7/cfitsio3430/imcompress.c
    patching file build/temp.linux-x86_64-3.7/cfitsio3430/imcompress.c
    checking file build/temp.linux-x86_64-3.7/cfitsio3430/putcols.c
    patching file build/temp.linux-x86_64-3.7/cfitsio3430/putcols.c
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking target system type... x86_64-unknown-linux-gnu
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/tmp/pip-install-ui7d52yl/fitsio/build/temp.linux-x86_64-3.7/cfitsio3430':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ui7d52yl/fitsio/setup.py", line 289, in <module>
        cmdclass={"build_ext": build_ext_subclass}
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-ui7d52yl/fitsio/setup.py", line 72, in run
        build_ext.run(self)
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/run/media/romain/e19863e1-bebc-4399-81a6-9807cb82a75c/anaconda/envs/py37/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-ui7d52yl/fitsio/setup.py", line 100, in build_extensions
        RANLIB=self.compiler.ranlib,
      File "/tmp/pip-install-ui7d52yl/fitsio/setup.py", line 227, in configure_cfitsio
        "could not configure cfitsio %s" % self.cfitsio_version)
    ValueError: could not configure cfitsio 3430
    
    ----------------------------------------

**Comment by beckermr** [comment] 2019-04-24 10:12
Try the conda package. See the readme for how to install it.

**Comment by esheldon** [comment] 2019-04-26 12:18
It looks like your environment doesn't have the compiler set up in a way that fitsio can use; but as @beckermr pointed out, you can now use the conda package which is pre-compiled, so it should avoid this problem.
```
conda install -c conda-forge fitsio
```

**Comment by beckermr** [comment] 2019-07-16 15:56
Closing this for now since it appears this was not a bug in the repo. If you still need help @astrom-tom, please reopen!

**Closed by beckermr** 2019-07-16 15:56 UTC
