### ISSUE TITLE
unittests (some fail) for tables with strings

### ISSUE THREAD

**Issue by sbailey** [esheldon/fitsio#99] opened 2016-08-30 19:40 UTC
Below are some unit tests for writing/reading structured arrays with strings in the columns, tested with fitsio 0.9.10 and numpy 1.11.1.

Under python 2.7, two of the tests fail due to #42 (trailing spaces added to strings...).  That seems hard to fix since it goes into the guts of cfitsio and the interpretation of the FITS standard, but would you consider adding a `fitsio.read()` option like `trim_whitespace` that would trim trailing whitespace upon request?  This would be somewhat analogous to the `lower/upper` options that modify the data but only upon request.

```
======================================================================
FAIL: test_io_strict (__main__.TestTable1DColumn)
test I/O roundtrip with strict matching
----------------------------------------------------------------------
Traceback (most recent call last):
  File "fitsio-table.py", line 33, in test_io_strict
    self.assertTrue(np.all(self.data['x'] == dx['x']), 'x: {} != {}'.format(self.data['x'], dx['x']))
AssertionError: x: ['abcde' 'xyz'] != ['abcde' 'xyz  ']
```

Under python 3.5, all 4 tests fail with the same basic error:

```
======================================================================
ERROR: test_io_strict (__main__.TestTable2DColumn)
test I/O roundtrip with strict matching
----------------------------------------------------------------------
Traceback (most recent call last):
  File "fitsio-table.py", line 29, in test_io_strict
    fitsio.write(self.testfile, self.data)
  File "/Users/sbailey/anaconda/envs/py3/lib/python3.5/site-packages/fitsio/fitslib.py", line 253, in write
    **keys)
  File "/Users/sbailey/anaconda/envs/py3/lib/python3.5/site-packages/fitsio/fitslib.py", line 486, in write
    table_type=table_type)
  File "/Users/sbailey/anaconda/envs/py3/lib/python3.5/site-packages/fitsio/fitslib.py", line 767, in write_table
    table_type=table_type)
  File "/Users/sbailey/anaconda/envs/py3/lib/python3.5/site-packages/fitsio/fitslib.py", line 857, in create_table_hdu
    names, formats, dims = array2tabledef(data, table_type=table_type)
  File "/Users/sbailey/anaconda/envs/py3/lib/python3.5/site-packages/fitsio/fitslib.py", line 3472, in array2tabledef
    name, form, dim = npy2fits(d,table_type=table_type)
  File "/Users/sbailey/anaconda/envs/py3/lib/python3.5/site-packages/fitsio/fitslib.py", line 3631, in npy2fits
    name, form, dim = npy_num2fits(d, table_type=table_type)
  File "/Users/sbailey/anaconda/envs/py3/lib/python3.5/site-packages/fitsio/fitslib.py", line 3657, in npy_num2fits
    raise ValueError("unsupported type '%s'" % npy_dtype)
ValueError: unsupported type 'U5'
```

Although it is true that the FITS format doesn't natively know about unicode, it seems that we should do something to be able to support the native string type of python3.  e.g. for consideration:
- downcast the unicode str to bytes upon writing and only raise an exception if the array contains non-ASCII unicode characters that can't be downcast.
- provide a `native_string` option to `fitsio.read` that would cast any FITS strings to the native string type for that version of python (py2.x: str=bytes='Sn', py3.x: str=unicode='Un')

That still seems clumsy but python 3 and native str=unicode is in our future whether we like it or not, so having some sort of support for it would be very handy.  A more formally correct solution would be to actually encode/decode the unicode and include in the header metadata what the encoding method is, but that starts to tread on the territory of standards (or at least registered conventions...).

If anyone reading this has been part of IAU FITS standard definition discussions and knows if there are specific guidelines or conventions for this already, please let us know.

The tests:

``` python
#- unit tests of fitsio with strings
#- Stephen Bailey, Lawrence Berkeley Lab

from __future__ import unicode_literals

import unittest
from uuid import uuid4
import os

import numpy as np
import fitsio

class _TestTable(unittest.TestCase):
    '''
    Base class for testing FITS tables.

    Subclass this and add setupClass to define self.data to test
    '''

    def setUp(self):
        self.testfile = 'test-{}.fits'.format(uuid4())

    def tearDown(self):
        if os.path.exists(self.testfile):
            os.remove(self.testfile)

    def test_io_strict(self):
        '''test I/O roundtrip with strict matching'''
        fitsio.write(self.testfile, self.data)
        dx = fitsio.read(self.testfile)
        self.assertEqual(self.data['x'].dtype, dx['x'].dtype)
        self.assertEqual(self.data['y'].dtype, dx['y'].dtype)
        self.assertTrue(np.all(self.data['x'] == dx['x']), 'x: {} != {}'.format(self.data['x'], dx['x']))
        self.assertTrue(np.all(self.data['y'] == dx['y']), 'y: {} != {}'.format(self.data['y'], dx['y']))

    def test_io_loose(self):
        '''test I/O roundtrip while ignoring trailing whitespace'''
        fitsio.write(self.testfile, self.data)
        dx = fitsio.read(self.testfile)
        self.assertEqual(self.data['x'].dtype, dx['x'].dtype)
        self.assertEqual(self.data['y'].dtype, dx['y'].dtype)
        #- Cast to chararray to strip trailing whitespace
        x = dx['x'].view(np.chararray)
        y = dx['y'].view(np.chararray)
        self.assertTrue(np.all(self.data['x'] == x), 'x: {} != {}'.format(self.data['x'], x))
        self.assertTrue(np.all(self.data['y'] == y), 'y: {} != {}'.format(self.data['y'], y))

class TestTable1DColumn(_TestTable):
    @classmethod
    def setUpClass(cls):
        dtype = [
            (str('x'), (str, 5)),    #- 1D column of 5-character strings
            (str('y'), (str, 3)),    #- !D column of 3-character strings
        ]
        data = np.zeros(2, dtype=dtype)
        data['x'] = ['abcde', 'xyz']
        data['y'] = ['A', 'BCX']
        cls.data = data

class TestTable2DColumn(_TestTable):
    @classmethod
    def setUpClass(cls):
        dtype = [
            (str('x'), (str, 5)),        #- 1D column of 5-character strings
            (str('y'), (str, 3), (4,)),  #- 2D column; each row is four 3-char strings
        ]
        data = np.zeros(2, dtype=dtype)
        data['x'] = ['abcde', 'xyz']
        data['y'][0] = ['A', 'BC', 'DEF', '123']
        data['y'][1] = ['X', 'YZ', 'PQR', '999']
        cls.data = data

if __name__ == '__main__':
    ### unittest.main()
    t1 = unittest.defaultTestLoader.loadTestsFromTestCase(TestTable1DColumn)
    t2 = unittest.defaultTestLoader.loadTestsFromTestCase(TestTable2DColumn)
    unittest.TextTestRunner(verbosity=2).run(unittest.TestSuite([t1,t2]))
```

**Comment by esheldon** [comment] 2016-08-30 20:30
I've a long time ago contacted the cfitsio maintainer about supporting the standard with regards to strings.  The standard says the string should be written with the trailing null preserved. cfitsio does not do this because it predates the standard, and the original fortran had no concept of null terminated strings.

I have also thought that adding a trim keyword would be the way to go, so we agree on that.

I'll have to think more about the rest.  Comments welcome from anyone.

**Comment by esheldon** [comment] 2016-08-30 20:31
Also note, modifying cfitsio to support (optionally) the standard is highly non-trivial.  I gave it a serious effort and failed miserably.  The maintainer did not want to attempt it.

**Comment by esheldon** [comment] 2016-09-01 14:37
I've implemented string trimming in master.  The syntax is as follows

You can ask for string trimming on construction:
```python
with fitsio.FITS(fname, trim_strings=True) as fits:
    data=fits.read()
```
or you can do it in a specific call to one of the read methods
```python
data=fitsio.read(fname, trim_strings=True)
with fitsio.FITS(fname, trim_strings=True) as fits:
    data=fits.read(trim_strings=True)
```
Let me know if what you think.

**Comment by sbailey** [comment] 2016-09-01 17:06
Thanks.  That interface looks good for trimming trailing whitespace from strings.

Just to be clear: If done within the python side this should use `str.rstrip()` or equivalent to trim only trailing whitespace, but not leading whitespace.  Agreed?

**Comment by esheldon** [comment] 2016-09-01 19:47
I'm using numpy.char.rstrip, which is vectorized

https://github.com/esheldon/fitsio/commit/32bbdb8374cb6204c9d53302affabe26b9b9e718#diff-59194934109d3b96481bdbdb3eadddccR4532

**Comment by sbailey** [comment] 2016-09-04 05:38
Here's an interesting counter example.  Using this example file: https://github.com/desihub/desitarget/blob/master/py/desitarget/test/t/tractor-3301m002.fits?raw=true

Column `type` has dtype `|S4` but c/fitsio doesn't auto-pad it with spaces:
```python
In [1]: a = fitsio.read('tractor-3301m002.fits')
   ...: a['type']
   ...: 
Out[1]: 
array(['PSF', 'DEV', 'EXP', 'EXP', 'DEV', 'DEV'], 
      dtype='|S4')
```
Writing it out and reading it back in then does have the unwanted spaces:
```python
In [2]: fitsio.write('blat.fits', a, clobber=True)
   ...: b = fitsio.read('blat.fits')
   ...: b['type']   #- now padded with spaces
   ...: 
Out[2]: 
array(['PSF ', 'DEV ', 'EXP ', 'EXP ', 'DEV ', 'DEV '], 
      dtype='|S4')
```
Inspecting the raw bytes of the files, tractor-3301m002.fits pads with nulls and blat.fits pads with spaces.  But I haven't figured out what is the relevant feature of tractor-3301m002.fits that causes c/fitsio to not pad the `type` column with spaces...

**Comment by esheldon** [comment] 2016-09-06 16:29
I'm guessing that the fields have embedded nulls, written by pyfits or another code

I think cfitsio will read exactly what bytes are there, the problem is writing.

**Comment by esheldon** [comment] 2018-03-20 16:31
can we close this one?

**Closed** 2019-04-10 17:05 UTC
