### ISSUE TITLE
current master is not py3 compatible

### ISSUE THREAD

**Issue by dneise** [esheldon/fitsio#95] opened 2016-08-11 06:11 UTC
The problems I reported in #94, were based on version 0.9.9.1 installed from pypi. 
I wanted to have a closer look myself and maybe even propose  a PR on this matter, so I installed the master, which also claims to be 0.9.9.1

But the master is not py3 compatible. The build does not fail on py3, but `import fitsio` fails.
I checked your `travis.yml` and saw that the build is performed, but the tests are not done, so you cannot see if everything works.

I have not much experience with travis, so I forked your repo and played around so I can find a minimalistic yml, which reproduces the error.

One can find the log on https://travis-ci.org/dneise/fitsio
and the minimalistic `travis.yml` here: https://github.com/dneise/fitsio/blob/master/.travis.yml

----

The version on pypi is py3 compatible, so I wondered what I did wrong. First I assumed you might have a dedicated py3 branch, but there are no active branches.

----

Then I ran `2to3` on `fitsio/fitslib.py`, which was enough to let me `import fitsio` successfully, 
but the tests now fail.

**Comment by esheldon** [comment] 2016-08-11 12:19
this command will not work from the build directory:
```
python fitsio/test.py
```
this is because python will try to load the package from the ./fitsio subdirectory rather than the the installed package, but that doesn't work.

better would be do change to a new directory (maybe /tmp?) and run
```
python -c "import fitsio; fitsio.test.test()"
```

**Comment by esheldon** [comment] 2016-08-11 12:20
Note I have confirmed master passes tests now on ubuntu with python 2.7 and 3.5, as well as os x with 2.7, 3.4, and 3.5

**Comment by dneise** [comment] 2016-08-11 13:36
I cannot confirm that:

I went back and forked your current master. Then pushed a minimum `.travis.yml` to build it on py3.5.2 and execute the tests. 

Have a look [here](https://travis-ci.org/dneise/fitsio/builds/151506884)
The [travis.yml](https://github.com/dneise/fitsio/blob/esheldons_master/.travis.yml)
~~~yml
language: python
python:
    - "3.5"

install:
    - pip install astropy 
    - pip list
    - pip install -e .
script:
    - cd /tmp
    - python -c "import fitsio; fitsio.test.test()"
~~~

----

As you can see it fails because of 

~~~python
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/travis/build/dneise/fitsio/fitsio/__init__.py", line 9, in <module>

    from . import fitslib

  File "/home/travis/build/dneise/fitsio/fitsio/fitslib.py", line 4607, in <module>

    _stypes = (str,unicode,numpy.string_)

NameError: name 'unicode' is not defined
~~~

And as I write this, `unicode` is still used in [line 4607 of the current master](https://github.com/esheldon/fitsio/blob/5399614a87b7504d95d8a25539af5236ca526596/fitsio/fitslib.py#L4607)

And as one can quickly check, `unicode` does not exist in py3 anymore:

~~~python
Python 3.5.2 |Anaconda 2.4.1 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> unicode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'unicode' is not defined
~~~

I can't find the mistake I made ... must somehow use a different version ...

**Comment by esheldon** [comment] 2016-08-11 13:42
It is still trying to load the local, not i nstalled code, see this line
```
File "/home/travis/build/dneise/fitsio/fitsio/__init__.py
```
that is not an installed package.

The unicodes all get converted on install using the build_py_2to3 .  See the setup.py file.  This is the only way things work on py3 at all.  This is again evidence that you are not installing fitsio.

Note your travis.yaml also does no install of fitsio.

**Comment by dneise** [comment] 2016-08-11 13:51
Ah aweseom ...  now I start to understand.

The line 
"pip install -e ." 
does install the package.

at least I though so.

But apparently it does not invoke the "build_py_2to3" part in the setup.py file. No idea why ... I will try to find it out.

**Comment by esheldon** [comment] 2016-08-11 13:53
Our travis file may be a place to start

https://github.com/esheldon/fitsio/blob/master/.travis.yml

**Comment by dneise** [comment] 2016-08-11 14:36
Okay, I think, I understood now what's going on.

Out of a habit, I called `pip install -e .`, which installs the package, but in `develop` mode.
Which is exactly the way I install packages on my system, when I plan to maybe work on them.

one can find more information about the development mode in [the setuptools docu](http://setuptools.readthedocs.io/en/latest/setuptools.html#development-mode) 

I think it is reasonable to assume when `pip install .` works, 
so does `pip install -e .`.

At the moment you do this 
~~~python
try:
    from distutils.command.build_py import build_py_2to3 as build_py
except ImportError:
    from distutils.command.build_py import build_py
~~~
to find out if the user is building on py2 or py3, but the development mode needs to be aware as well to function properly, so by getting rid of that `try ... except` and instead doing
~~~python
setup(name="fitsio", 
     # ....
      use_2to3=True,
      cmdclass = {
        "build_ext": build_ext_subclass}
     )
~~~
you gain "pip -e"-installability.

**Comment by dneise** [comment] 2016-08-11 15:14
However using `use_2to3` does not help, when using `py.test`, since pytest keeps importing the local code instead of the py3 version, and then throws the "unicode is not defined" error.

There is a [blog post](https://www.hackzine.org/python-testing-with-pytest-and-2to3-plus-tox-and-travis-ci.html) which explains how to integrate distutils using 2to3 and pytest. 

But I don't know, if you want to use pytest in this project or something else.

**Comment by esheldon** [comment] 2016-08-11 15:22
thanks for the pointers, I'll try to look into it at some point.

**Comment by esheldon** [comment] 2016-08-11 16:13
The python3 compatibility stuff was pretty minor, so I just went through and fixed it by hand.

now 2to3 is no longer needed.  I've pushed this to master

**Comment by dneise** [comment] 2016-08-17 14:05
In case you are interested, I think this can be closed.

**Comment by esheldon** [comment] 2016-08-17 14:27
ok, I'll close it.

Note as the opener you can always close it yourself as well.

**Closed by esheldon** 2016-08-17 14:27 UTC
